print("\n\n\t\t\t-------------------MAD LIB GENERATOR GAME-------------------\n\n")
print("\n\n\tHEYAAAAAA GUYSS!!! WELCOME TO THIS INTERESTING GAME WHERE YOU CAN MAKE A STORY OF YOUR OWN!!\n\tSOOOOOOO...LET'S BEGIN...\n\n ")
Word1=input("\n\tGive a noun:\n\t")
Word2=input("\n\tGive another naming word:\n\t")
Word3=input("\n\tGive any adjective:\n\t")
Word4=input("\n\tGive a noun:\n\t")
Word5=input("\n\tEnter any noun:\n\t")
Word6=input("\n\tGive a naming word:\n\t")
Word7=input("\n\tEnter an adjective:\n\t")
Word8=input("\n\tGive any plural noun:\n\t")
Word9=input("\n\tName any noun(plural):\n\t")
Word10=input("\n\tGive any adjective\n\t")
Word11=input("\n\tEnter any plural noun\n\t")
Word12=input("\n\tEnter any plural noun\n\t")
Word13=input("\n\tEnter any adjective:\n\t")
Word14=input("\n\tEnter a noun:\n\t")
Word15=input("\n\tEnter an adjective:\n\t")
Story="\nA striking painting of Great-Grandma as a young {word1} has been hanging in our {word2} for as long as I can remember.A local art dealer believes it was painted by James McNeill Whistler, whose most {word3} work is the painting of his {word4} sitting on a {word5}.It could be true. After all, Great- Grandma was the reigning {word6} of her day. With her  {word7} complexion, high check-{word8} and vivid  green {word9}, there wasn't a portrait artist alive who didn't want to paint her.And she had no end of {word10} suitors.Over the years she was courted by crowned {word11} of Europe as well as the leading {word12} of American society.I've often wonderedwhy she married Great-Grandpa, because to tell the truth, he was kind of {word13}-looking.When I asked Dad about it, he said that Great Grandpa was the only {word14} who could make her laugh.Isn't love {word15}?!\n\n\n\n "
print("\n\n\tOOHOOOOOO!!!!!!!!!!! The Story is ready!!!!!!!!!!!!!!!!!!!\n\n\t")
print("\n\n\t\t\t\t\t\t PORTRAIT OF GREAT-GRANDMA\n ")
print(Story.format(word1=Word1,word2=Word2,word3=Word3,word4=Word4,word5=Word5,word6=Word6,word7=Word7,word8=Word8,word9=Word9,word10=Word10,word11=Word11,word12=Word12,word13=Word13,word14=Word14,word15=Word15))
